version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/typescript"
    schedule:
      interval: "weekly"

  # Enable version updates for github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "weekly"
